# Generated by Django 4.2.6 on 2023-10-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_guest',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.SmallIntegerField(default=0),
        ),
    ]
